//! Embeds the `stdlib/` sources into the `hella` binary so `hella setup` can
//! install them to `~/.hella/lib` on machines without a repo checkout.
//! The file list is generated (sorted `**/*.hll` under `../stdlib`), so
//! adding a module needs no build-script change.

use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=../stdlib");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let stdlib = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../stdlib");

    let mut rels: Vec<String> = Vec::new();
    collect_hll(&stdlib, &stdlib, &mut rels);
    rels.sort();

    let mut out = String::from(
        "/// Embedded standard-library sources: `(relative path, contents)`.\n\
         /// Generated by `crates/hella-cli/build.rs` from `stdlib/**/*.hll`.\n\
         pub const STDLIB_FILES: &[(&str, &str)] = &[\n",
    );
    for rel in &rels {
        out.push_str(&format!(
            "    ({rel:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../stdlib/{rel}\"))),\n"
        ));
    }
    out.push_str("];\n");
    std::fs::write(out_dir.join("stdlib_embedded.rs"), out).unwrap();
}

fn collect_hll(root: &PathBuf, dir: &PathBuf, out: &mut Vec<String>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_hll(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "hll")
            && let Ok(rel) = path.strip_prefix(root)
        {
            out.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
}
