[package]
name = "hella"
version = "0.1.0"
edition = "2024"

[dependencies]
hella-compiler = { path = "../hella-compiler" }
hella-fmt = { path = "../hella-fmt" }
hella-lsp = { path = "../hella-lsp" }
clap = { version = "4", features = ["derive"] }
anstyle = "1"
miette = { version = "7", features = ["fancy"] }
console = "0.16"
indicatif = "0.18.6"
inkwell = { version = "0.10", features = ["llvm21-1"] }

[[bin]]
name = "hella"
path = "src/main.rs"
